// Generated by sonnet-3.5
export interface CobaltRequest {
	url: string;
	videoQuality?:
		| "144"
		| "240"
		| "360"
		| "480"
		| "720"
		| "1080"
		| "1440"
		| "2160"
		| "4320"
		| "max";
	audioFormat?: "best" | "mp3" | "ogg" | "wav" | "opus";
	audioBitrate?: "320" | "256" | "128" | "96" | "64" | "8";
	filenameStyle?: "classic" | "pretty" | "basic" | "nerdy";
	downloadMode?: "auto" | "audio" | "mute";
	youtubeVideoCodec?: "h264" | "av1" | "vp9";
	youtubeDubLang?: string;
	alwaysProxy?: boolean;
	disableMetadata?: boolean;
	tiktokFullAudio?: boolean;
	tiktokH265?: boolean;
	twitterGif?: boolean;
	youtubeHLS?: boolean;
}

export interface CobaltResponse {
	status: "error" | "picker" | "redirect" | "tunnel";
	url?: string;
	filename?: string;
	audio?: string;
	audioFilename?: string;
	picker?: CobaltPickerItem[];
	error?: CobaltError;
}

export interface CobaltPickerItem {
	type: "photo" | "video" | "gif";
	url: string;
	thumb?: string;
}

export interface CobaltError {
	code: string;
	context?: {
		service?: string;
		limit?: number;
	};
}

export interface CobaltServerInfo {
	cobalt: {
		version: string;
		url: string;
		startTime: string;
		durationLimit: number;
		services: string[];
	};
	git: {
		commit: string;
		branch: string;
		remote: string;
	};
}
